using RentalOS.Domain.Enums;

namespace RentalOS.Application.Modules.Invoices.Queries;

public class InvoiceDto
{
    public Guid Id { get; set; }
    public string InvoiceCode { get; set; } = string.Empty;
    public Guid ContractId { get; set; }
    public string? CustomerName { get; set; }
    public string? RoomNumber { get; set; }
    public string? PropertyName { get; set; }
    public DateOnly BillingMonth { get; set; }
    public DateOnly DueDate { get; set; }
    public decimal TotalAmount { get; set; }
    public InvoiceStatus Status { get; set; }
    public decimal? PartialPaidAmount { get; set; }
    public string? PaymentLinkToken { get; set; }
    public DateTime? SentAt { get; set; }
    public DateTime? PaidAt { get; set; }
    public string? PdfUrl { get; set; }
    public bool IsAutoGenerated { get; set; }

    // Readings
    public int ElectricityOld { get; set; }
    public int ElectricityNew { get; set; }
    public decimal ElectricityPrice { get; set; }
    public decimal ElectricityAmount { get; set; }
    public int WaterOld { get; set; }
    public int WaterNew { get; set; }
    public decimal WaterPrice { get; set; }
    public decimal WaterAmount { get; set; }

    // Fees
    public decimal RoomRent { get; set; }
    public decimal ServiceFee { get; set; }
    public decimal InternetFee { get; set; }
    public decimal GarbageFee { get; set; }
    public decimal OtherFees { get; set; }
    public string? OtherFeesNote { get; set; }
    public decimal Discount { get; set; }
    public string? DiscountNote { get; set; }
    public string? Notes { get; set; }
}
