version: "3.9"

services:
  db:
    image: postgres:16
    container_name: rentalos-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: rentalos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "20102001"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
