$baseUrl = "http://localhost:5272"

function Get-Token($email, $password, $slug) {
    try {
        $body = "{`"email`":`"$email`",`"password`":`"$password`",`"tenantSlug`":`"$slug`"}"
        $r = Invoke-WebRequest -Uri "$baseUrl/api/v1/auth/login" -Method POST -Body $body -ContentType "application/json" -UseBasicParsing
        $data = $r.Content | ConvertFrom-Json
        return $data.accessToken
    } catch { return $null }
}

function Probe($method, $path, $token, $body = $null) {
    try {
        $headers = @{ Authorization = "Bearer $token" }
        $params = @{ Uri = "$baseUrl$path"; Method = $method; Headers = $headers; UseBasicParsing = $true }
        if ($body) { $params.Body = $body; $params.ContentType = "application/json" }
        $r = Invoke-WebRequest @params
        Write-Host "[OK $($r.StatusCode)] $method $path"
    } catch {
        $resp = $_.Exception.Response
        if ($resp) {
            $stream = $resp.GetResponseStream()
            $reader = New-Object System.IO.StreamReader($stream)
            $content = $reader.ReadToEnd()
            Write-Host "[ERR $([int]$resp.StatusCode)] $method $path -> $content"
        } else {
            Write-Host "[EXC] $method $path -> $_"
        }
    }
}

$token = Get-Token "owner@testco5174.com" "Test@123456!" "test-company-testco5174"
Write-Host "Token OK: $($token -ne $null)"

# Settings
Probe "PUT" "/api/v1/settings/company" $token '{"name":"Test","address":"123 St","phone":"0900000000","email":"t@t.com","taxCode":"","logoUrl":""}'
Probe "PUT" "/api/v1/settings/billing" $token '{"autoGenerateDay":5,"paymentDueDays":10,"remindBeforeDays":[3,1],"remindOverdueDays":[1,3,7]}'

# Properties
Probe "POST" "/api/v1/properties" $token '{"name":"Test House","address":"123 Street","city":"Hanoi","ward":"Ward1","description":"","totalRooms":5}'

# Customers
Probe "POST" "/api/v1/customers" $token '{"fullName":"Nguyen Van A","phone":"0900000001","email":"customer@test.com","idCardNumber":"012345678901","dateOfBirth":"1990-01-01","address":"456 Street"}'

# Transactions export
Probe "GET" "/api/v1/transactions/export" $token

# Collection rate
Probe "GET" "/api/v1/reports/collection-rate" $token

# Monthly report
Probe "GET" "/api/v1/reports/monthly?month=2025-01" $token

# Notifications mark-all-read
Probe "POST" "/api/v1/notifications/mark-all-read" $token '{}'

# Invoices bulk-generate
Probe "POST" "/api/v1/invoices/bulk-generate" $token '{"billingMonth":"2025-01","propertyId":null}'
