using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using RentalOS.Domain.Entities;

namespace RentalOS.Infrastructure.Persistence.Configurations;

public class InvoiceConfiguration : IEntityTypeConfiguration<Invoice>
{
    public void Configure(EntityTypeBuilder<Invoice> b)
    {
        b.ToTable("invoices");
        b.HasKey(i => i.Id);
        b.HasIndex(i => i.InvoiceCode).IsUnique();
        b.HasIndex(i => i.PaymentLinkToken).IsUnique()
            .HasFilter("payment_link_token IS NOT NULL");
        // Unique billing month per contract (excluding cancelled)
        b.HasIndex(i => new { i.ContractId, i.BillingMonth })
            .IsUnique().HasFilter("status != 'cancelled'");

        b.Property(i => i.InvoiceCode).HasMaxLength(50).IsRequired();
        b.Property(i => i.BillingMonth).HasColumnType("date").IsRequired();
        b.Property(i => i.DueDate).HasColumnType("date").IsRequired();
        b.Property(i => i.ElectricityPrice).HasColumnType("decimal(8,2)").IsRequired();
        b.Property(i => i.WaterPrice).HasColumnType("decimal(8,2)").IsRequired();
        b.Property(i => i.InternetFee).HasColumnType("decimal(10,2)").HasDefaultValue(0m);
        b.Property(i => i.GarbageFee).HasColumnType("decimal(10,2)").HasDefaultValue(0m);
        b.Property(i => i.RoomRent).HasColumnType("decimal(12,2)").IsRequired();
        b.Property(i => i.ServiceFee).HasColumnType("decimal(10,2)").HasDefaultValue(0m);
        b.Property(i => i.OtherFees).HasColumnType("decimal(10,2)").HasDefaultValue(0m);
        b.Property(i => i.OtherFeesNote).HasMaxLength(200);
        b.Property(i => i.Discount).HasColumnType("decimal(10,2)").HasDefaultValue(0m);
        b.Property(i => i.DiscountNote).HasMaxLength(200);
        b.Property(i => i.ElectricityAmount).HasColumnType("decimal(12,2)").HasDefaultValue(0m);
        b.Property(i => i.WaterAmount).HasColumnType("decimal(12,2)").HasDefaultValue(0m);
        b.Property(i => i.TotalAmount).HasColumnType("decimal(12,2)").IsRequired();
        b.Property(i => i.Status).HasConversion<string>().HasMaxLength(20).HasDefaultValue("pending");
        b.Property(i => i.PartialPaidAmount).HasColumnType("decimal(12,2)");
        b.Property(i => i.PaymentLinkToken).HasMaxLength(100);
        b.Property(i => i.PdfUrl).HasMaxLength(500);
        b.Property(i => i.MeterImageElectricity).HasMaxLength(500);
        b.Property(i => i.MeterImageWater).HasMaxLength(500);
        b.Property(i => i.IsAutoGenerated).HasDefaultValue(false);

        b.HasOne(i => i.Contract).WithMany(c => c.Invoices).HasForeignKey(i => i.ContractId);
        b.HasIndex(i => i.ContractId);
        b.HasIndex(i => i.Status);
        b.HasIndex(i => i.BillingMonth);
    }
}
