using MediatR;
using Microsoft.EntityFrameworkCore;
using RentalOS.Application.Common.Interfaces;
using RentalOS.Application.Common.Models;

namespace RentalOS.Application.Modules.Invoices.Queries.GetInvoiceById;

public record GetInvoiceByIdQuery(Guid Id) : IRequest<Result<InvoiceDto>>;

public class GetInvoiceByIdQueryHandler : IRequestHandler<GetInvoiceByIdQuery, Result<InvoiceDto>>
{
    private readonly IApplicationDbContext _context;
    private readonly ICurrentUserService _currentUserService;

    public GetInvoiceByIdQueryHandler(IApplicationDbContext context, ICurrentUserService currentUserService)
    {
        _context = context;
        _currentUserService = currentUserService;
    }

    public async Task<Result<InvoiceDto>> Handle(GetInvoiceByIdQuery request, CancellationToken cancellationToken)
    {
        var query = _context.Invoices
            .Include(i => i.Contract)
                .ThenInclude(c => c.Customer)
            .Include(i => i.Contract)
                .ThenInclude(c => c.Room)
                    .ThenInclude(r => r.Property)
            .AsNoTracking()
            .Where(i => i.Id == request.Id)
            .AsQueryable();

        if (string.Equals(_currentUserService.Role, "tenant", StringComparison.OrdinalIgnoreCase))
        {
            var currentUserId = Guid.TryParse(_currentUserService.UserId, out var parsedUserId) ? parsedUserId : Guid.Empty;
            var currentUserEmail = await _context.ApplicationUsers
                .Where(u => u.Id == currentUserId)
                .Select(u => u.Email)
                .FirstOrDefaultAsync(cancellationToken);

            if (!string.IsNullOrWhiteSpace(currentUserEmail))
            {
                query = query.Where(i => i.Contract.Customer.Email == currentUserEmail);
            }
        }

        var invoice = await query
            .Select(i => new InvoiceDto
            {
                Id = i.Id,
                InvoiceCode = i.InvoiceCode,
                ContractId = i.ContractId,
                CustomerName = i.Contract.Customer.FullName,
                RoomNumber = i.Contract.Room.RoomNumber,
                PropertyName = i.Contract.Room.Property.Name,
                BillingMonth = i.BillingMonth,
                DueDate = i.DueDate,
                TotalAmount = i.TotalAmount,
                Status = i.Status,
                PartialPaidAmount = i.PartialPaidAmount,
                PaymentLinkToken = i.PaymentLinkToken,
                SentAt = i.SentAt,
                PaidAt = i.PaidAt,
                PdfUrl = i.PdfUrl,
                IsAutoGenerated = i.IsAutoGenerated,
                ElectricityOld = i.ElectricityOld,
                ElectricityNew = i.ElectricityNew,
                ElectricityPrice = i.ElectricityPrice,
                ElectricityAmount = i.ElectricityAmount,
                WaterOld = i.WaterOld,
                WaterNew = i.WaterNew,
                WaterPrice = i.WaterPrice,
                WaterAmount = i.WaterAmount,
                RoomRent = i.RoomRent,
                ServiceFee = i.ServiceFee,
                InternetFee = i.InternetFee,
                GarbageFee = i.GarbageFee,
                OtherFees = i.OtherFees,
                OtherFeesNote = i.OtherFeesNote,
                Discount = i.Discount,
                DiscountNote = i.DiscountNote,
                Notes = i.Notes,
            })
            .FirstOrDefaultAsync(cancellationToken);

        if (invoice == null) return Result<InvoiceDto>.Fail("INVOICE_NOT_FOUND", "Không tìm thấy hóa đơn.");
        return Result<InvoiceDto>.Ok(invoice);
    }
}
