using MediatR;
using Microsoft.EntityFrameworkCore;
using RentalOS.Application.Common.Interfaces;
using RentalOS.Application.Common.Models;
using RentalOS.Domain.Enums;

namespace RentalOS.Application.Modules.Invoices.Queries.GetPendingMeter;

public record GetPendingMeterInvoicesQuery : IRequest<Result<List<InvoiceDto>>>
{
    public Guid? PropertyId { get; init; }
    public DateOnly? BillingMonth { get; init; }
}

public class GetPendingMeterInvoicesQueryHandler(IApplicationDbContext context) 
    : IRequestHandler<GetPendingMeterInvoicesQuery, Result<List<InvoiceDto>>>
{
    public async Task<Result<List<InvoiceDto>>> Handle(GetPendingMeterInvoicesQuery request, CancellationToken cancellationToken)
    {
        // "Pending Meter" là những invoice tự động tạo (IsAutoGenerated) mà ElectricityNew == ElectricityOld (hoặc Water...)
        // Ở đây tôi sẽ lọc theo Status == Pending và IsAutoGenerated.
        var query = context.Invoices
            .Include(i => i.Contract)
                .ThenInclude(c => c.Customer)
            .Include(i => i.Contract)
                .ThenInclude(c => c.Room)
                    .ThenInclude(r => r.Property)
            .Where(i => i.Status == InvoiceStatus.Pending && i.IsAutoGenerated)
            .AsNoTracking();

        if (request.PropertyId.HasValue)
            query = query.Where(i => i.Contract.Room.PropertyId == request.PropertyId.Value);

        if (request.BillingMonth.HasValue)
        {
            var firstDay = new DateOnly(request.BillingMonth.Value.Year, request.BillingMonth.Value.Month, 1);
            query = query.Where(i => i.BillingMonth == firstDay);
        }

        var result = await query
            .OrderBy(i => i.Contract.Room.RoomNumber)
            .Select(i => new InvoiceDto
            {
                Id = i.Id,
                InvoiceCode = i.InvoiceCode,
                ContractId = i.ContractId,
                CustomerName = i.Contract.Customer.FullName,
                RoomNumber = i.Contract.Room.RoomNumber,
                PropertyName = i.Contract.Room.Property.Name,
                BillingMonth = i.BillingMonth,
                DueDate = i.DueDate,
                TotalAmount = i.TotalAmount,
                Status = i.Status,
                IsAutoGenerated = i.IsAutoGenerated,
                ElectricityOld = i.ElectricityOld,
                ElectricityNew = i.ElectricityNew,
                WaterOld = i.WaterOld,
                WaterNew = i.WaterNew
            })
            .ToListAsync(cancellationToken);

        return Result<List<InvoiceDto>>.Ok(result);
    }
}
