namespace RentalOS.Application.Modules.Settings.Dtos;

public class MoMoSettingsDto
{
    public string PartnerCode { get; set; } = string.Empty;
    public string AccessKey { get; set; } = string.Empty;
    public string SecretKey { get; set; } = string.Empty;
    public bool IsActive { get; set; }
}

public class VNPaySettingsDto
{
    public string TmnCode { get; set; } = string.Empty;
    public string HashSecret { get; set; } = string.Empty;
    public bool IsActive { get; set; }
}

public class BankSettingsDto
{
    public string BankName { get; set; } = string.Empty;
    public string AccountNumber { get; set; } = string.Empty;
    public string AccountName { get; set; } = string.Empty;
    public string? Branch { get; set; }
    public bool IsActive { get; set; }
}

public class CompanySettingsDto
{
    public string CompanyName { get; set; } = string.Empty;
    public string Address { get; set; } = string.Empty;
    public string Phone { get; set; } = string.Empty;
    public string Email { get; set; } = string.Empty;
    public string? TaxCode { get; set; }
    public string? LogoUrl { get; set; }
}

public class BillingSettingsDto
{
    public int AutoGenerateDay { get; set; } = 5;
    public int PaymentDueDays { get; set; } = 10;
    public int[] RemindBeforeDueDays { get; set; } = { 3, 1 };
    public int[] RemindOverdueDays { get; set; } = { 1, 3, 7 };
    public decimal DefaultElectricityPrice { get; set; } = 3500;
    public decimal DefaultWaterPrice { get; set; } = 15000;
    public decimal DefaultServiceFee { get; set; } = 50000;
    public bool AutoSendNotification { get; set; } = true;
}

public class AllSettingsDto
{
    public MoMoSettingsDto MoMo { get; set; } = new();
    public VNPaySettingsDto VNPay { get; set; } = new();
    public BankSettingsDto Bank { get; set; } = new();
    public CompanySettingsDto Company { get; set; } = new();
    public BillingSettingsDto Billing { get; set; } = new();
}
