using RentalOS.Domain.Enums;

namespace RentalOS.Domain.Entities;

/// <summary>Monthly invoice generated for a rental contract — bảng 9.</summary>
public class Invoice : BaseEntity
{
    /// <summary>Human-readable invoice code (e.g. "HD-2024-001/5").</summary>
    public string InvoiceCode { get; set; } = string.Empty;

    /// <summary>FK to the associated contract.</summary>
    public Guid ContractId { get; set; }

    /// <summary>First day of the billing month (stored as date, e.g. 2024-05-01).</summary>
    public DateOnly BillingMonth { get; set; }

    /// <summary>Payment due date.</summary>
    public DateOnly DueDate { get; set; }

    // ── Electricity ──────────────────────────────────────
    /// <summary>Previous electricity meter reading (kWh).</summary>
    public int ElectricityOld { get; set; } = 0;

    /// <summary>Current electricity meter reading (kWh).</summary>
    public int ElectricityNew { get; set; } = 0;

    /// <summary>Price per kWh at the time of invoice generation (VND).</summary>
    public decimal ElectricityPrice { get; set; }

    // ── Water ────────────────────────────────────────────
    /// <summary>Previous water meter reading (m³).</summary>
    public int WaterOld { get; set; } = 0;

    /// <summary>Current water meter reading (m³).</summary>
    public int WaterNew { get; set; } = 0;

    /// <summary>Price per m³ at the time of invoice generation (VND).</summary>
    public decimal WaterPrice { get; set; }

    // ── Fees ─────────────────────────────────────────────
    /// <summary>Fixed monthly internet fee. MỚI.</summary>
    public decimal InternetFee { get; set; } = 0;

    /// <summary>Fixed monthly garbage collection fee. MỚI.</summary>
    public decimal GarbageFee { get; set; } = 0;

    /// <summary>Base monthly room rent.</summary>
    public decimal RoomRent { get; set; }

    /// <summary>Monthly service fee.</summary>
    public decimal ServiceFee { get; set; } = 0;

    /// <summary>Miscellaneous other fees.</summary>
    public decimal OtherFees { get; set; } = 0;

    /// <summary>Description of other fees.</summary>
    public string? OtherFeesNote { get; set; }

    /// <summary>Discount amount applied.</summary>
    public decimal Discount { get; set; } = 0;

    /// <summary>Description / reason for the discount.</summary>
    public string? DiscountNote { get; set; }

    // ── Computed totals ───────────────────────────────────
    /// <summary>Calculated electricity cost (ElectricityNew - ElectricityOld) × ElectricityPrice.</summary>
    public decimal ElectricityAmount { get; set; } = 0;

    /// <summary>Calculated water cost (WaterNew - WaterOld) × WaterPrice.</summary>
    public decimal WaterAmount { get; set; } = 0;

    /// <summary>Grand total amount due.</summary>
    public decimal TotalAmount { get; set; }

    // ── Status ───────────────────────────────────────────
    /// <summary>Current payment status.</summary>
    public InvoiceStatus Status { get; set; } = InvoiceStatus.Pending;

    /// <summary>Amount already received for a partial payment. MỚI.</summary>
    public decimal? PartialPaidAmount { get; set; }

    // ── Payment link ─────────────────────────────────────
    /// <summary>Secure token for the public payment link.</summary>
    public string? PaymentLinkToken { get; set; }

    /// <summary>Expiry of the payment link.</summary>
    public DateTime? PaymentLinkExpiresAt { get; set; }

    // ── Metadata ─────────────────────────────────────────
    /// <summary>Internal notes.</summary>
    public string? Notes { get; set; }

    /// <summary>URL of the generated invoice PDF.</summary>
    public string? PdfUrl { get; set; }

    /// <summary>Photo of the electricity meter reading. MỚI.</summary>
    public string? MeterImageElectricity { get; set; }

    /// <summary>Photo of the water meter reading. MỚI.</summary>
    public string? MeterImageWater { get; set; }

    /// <summary>True when this invoice was auto-generated by a background job. MỚI.</summary>
    public bool IsAutoGenerated { get; set; } = false;

    /// <summary>Timestamp when the notification was sent to the customer. MỚI.</summary>
    public DateTime? SentAt { get; set; }

    /// <summary>Timestamp when full payment was received. MỚI.</summary>
    public DateTime? PaidAt { get; set; }

    /// <summary>FK to the user who manually created this invoice.</summary>
    public Guid? CreatedBy { get; set; }

    // Navigation
    public Contract Contract { get; set; } = null!;
    public ICollection<Transaction> Transactions { get; set; } = [];
    public ICollection<PaymentLinkLog> PaymentLinkLogs { get; set; } = [];
}
