// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RentalOS.Infrastructure.Persistence;

#nullable disable

namespace RentalOS.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260328041607_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RentalOS.Domain.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("Vietnam")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("state");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("street");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("zip_code");

                    b.HasKey("Id")
                        .HasName("p_k_addresses");

                    b.HasIndex("PropertyId")
                        .HasDatabaseName("i_x_addresses_property_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_addresses_user_id");

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("RentalOS.Domain.Entities.AiConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_message_at");

                    b.Property<int>("MessageCount")
                        .HasColumnType("integer")
                        .HasColumnName("message_count");

                    b.Property<string>("Messages")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("messages");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_ai_conversations");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_ai_conversations_user_id");

                    b.ToTable("ai_conversations", (string)null);
                });

            modelBuilder.Entity("RentalOS.Domain.Entities.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("RentalOS.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EntityCode")
                        .HasColumnType("text")
                        .HasColumnName("entity_code");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_value");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("p_k_audit_logs");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("i_x_audit_logs_created_at");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("RentalOS.Domain.Entities.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BillingDate")
                        .HasColumnType("integer")
                        .HasColumnName("billing_date");

                    b.Property<string>("ContractCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("contract_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<decimal>("DepositAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("deposit_amount");

                    b.Property<int>("DepositMonths")
                        .HasColumnType("integer")
                        .HasColumnName("deposit_months");

                    b.Property<bool>("DepositPaid")
                        .HasColumnType("boolean")
                        .HasColumnName("deposit_paid");

                    b.Property<DateTime?>("DepositPaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deposit_paid_at");

                    b.Property<decimal?>("DepositRefunded")
                        .HasColumnType("numeric")
                        .HasColumnName("deposit_refunded");

                    b.Property<decimal?>("ElectricityPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("electricity_price");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<decimal?>("GarbageFee")
                        .HasColumnType("numeric")
                        .HasColumnName("garbage_fee");

                    b.Property<decimal?>("InternetFee")
                        .HasColumnType("numeric")
                        .HasColumnName("internet_fee");

                    b.Property<int>("MaxOccupants")
                        .HasColumnType("integer")
                        .HasColumnName("max_occupants");

                    b.Property<decimal>("MonthlyRent")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monthly_rent");

                    b.Property<int>("PaymentDueDays")
                        .HasColumnType("integer")
                        .HasColumnName("payment_due_days");

                    b.Property<string>("PdfUrl")
                        .HasColumnType("text")
                        .HasColumnName("pdf_url");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<decimal?>("ServiceFee")
                        .HasColumnType("numeric")
                        .HasColumnName("service_fee");

                    b.Property<DateTime?>("SignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("signed_at");

                    b.Property<bool>("SignedByCustomer")
                        .HasColumnType("boolean")
                        .HasColumnName("signed_by_customer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TemplateId")
                        .HasColumnType("text")
                        .HasColumnName("template_id");

                    b.Property<DateTime?>("TerminatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("terminated_at");

                    b.Property<string>("TerminationReason")
                        .HasColumnType("text")
                        .HasColumnName("termination_reason");

                    b.Property<string>("TerminationType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("termination_type");

                    b.Property<string>("Terms")
                        .HasColumnType("text")
                        .HasColumnName("terms");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("WaterPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("water_price");

                    b.HasKey("Id")
                        .HasName("p_k_contracts");

                    b.HasIndex("ContractCode")
                        .IsUnique()
                        .HasDatabaseName("i_x_contracts_contract_code");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("i_x_contracts_customer_id");

                    b.HasIndex("EndDate")
                        .HasDatabaseName("i_x_contracts_end_date")
                        .HasFilter("\"Status\" = 0");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("i_x_contracts_room_id");

                    b.ToTable("contracts", (string)null);
                });

            modelBuilder.Entity("RentalOS.Domain.Entities.ContractCoTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<DateOnly?>("MovedInAt")
                        .HasColumnType("date")
                        .HasColumnName("moved_in_at");

                    b.Property<DateOnly?>("MovedOutAt")
                        .HasColumnType("date")
                        .HasColumnName("moved_out_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_contract_co_tenants");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("i_x_contract_co_tenants_customer_id");

                    b.HasIndex("ContractId", "CustomerId")
                        .IsUnique()
                        .HasDatabaseName("i_x_contract_co_tenants_contract_id_customer_id");

                    b.ToTable("contract_co_tenants", (string)null);
                });

            modelBuilder.Entity("RentalOS.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlacklistReason")
                        .HasColumnType("text")
                        .HasColumnName("blacklist_reason");

                    b.Property<DateTime?>("BlacklistedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("blacklisted_at");

                    b.Property<Guid?>("BlacklistedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("blacklisted_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentAddress")
                        .HasColumnType("text")
                        .HasColumnName("current_address");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("EmergencyContactName")
                        .HasColumnType("text")
                        .HasColumnName("emergency_contact_name");

                    b.Property<string>("EmergencyContactPhone")
                        .HasColumnType("text")
                        .HasColumnName("emergency_contact_phone");

                    b.Property<string>("EmergencyContactRelationship")
                        .HasColumnType("text")
                        .HasColumnName("emergency_contact_relationship");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<string>("Hometown")
                        .HasColumnType("text")
                        .HasColumnName("hometown");

                    b.Property<string>("IdCardImageBack")
                        .HasColumnType("text")
                        .HasColumnName("id_card_image_back");

                    b.Property<string>("IdCardImageFront")
                        .HasColumnType("text")
                        .HasColumnName("id_card_image_front");

                    b.Property<string>("IdCardNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id_card_number");

                    b.Property<bool>("IsBlacklisted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_blacklisted");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Occupation")
                        .HasColumnType("text")
                        .HasColumnName("occupation");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("PortraitImage")
                        .HasColumnType("text")
                        .HasColumnName("portrait_image");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Workplace")
                        .HasColumnType("text")
                        .HasColumnName("workplace");

                    b.HasKey("Id")
                        .HasName("p_k_customers");

                    b.HasIndex("IdCardNumber")
                        .HasDatabaseName("i_x_customers_id_card_number");

                    b.HasIndex("Phone")
                        .HasDatabaseName("i_x_customers_phone");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("RentalOS.Domain.Entities.InAppNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_in_app_notifications");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("i_x_in_app_notifications_created_at");

                    b.HasIndex("UserId", "IsRead")
                        .HasDatabaseName("i_x_in_app_notifications_user_id_is_read");

                    b.ToTable("in_app_notifications", (string)null);
                });

            modelBuilder.Entity("RentalOS.Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("BillingMonth")
                        .HasColumnType("date")
                        .HasColumnName("billing_month");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<decimal>("Discount")
                        .HasColumnType("numeric")
                        .HasColumnName("discount");

                    b.Property<string>("DiscountNote")
                        .HasColumnType("text")
                        .HasColumnName("discount_note");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<decimal>("ElectricityAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("electricity_amount");

                    b.Property<int>("ElectricityNew")
                        .HasColumnType("integer")
                        .HasColumnName("electricity_new");

                    b.Property<int>("ElectricityOld")
                        .HasColumnType("integer")
                        .HasColumnName("electricity_old");

                    b.Property<decimal>("ElectricityPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("electricity_price");

                    b.Property<decimal>("GarbageFee")
                        .HasColumnType("numeric")
                        .HasColumnName("garbage_fee");

                    b.Property<decimal>("InternetFee")
                        .HasColumnType("numeric")
                        .HasColumnName("internet_fee");

                    b.Property<string>("InvoiceCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("invoice_code");

                    b.Property<bool>("IsAutoGenerated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_auto_generated");

                    b.Property<string>("MeterImageElectricity")
                        .HasColumnType("text")
                        .HasColumnName("meter_image_electricity");

                    b.Property<string>("MeterImageWater")
                        .HasColumnType("text")
                        .HasColumnName("meter_image_water");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal>("OtherFees")
                        .HasColumnType("numeric")
                        .HasColumnName("other_fees");

                    b.Property<string>("OtherFeesNote")
                        .HasColumnType("text")
                        .HasColumnName("other_fees_note");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<decimal?>("PartialPaidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("partial_paid_amount");

                    b.Property<DateTime?>("PaymentLinkExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payment_link_expires_at");

                    b.Property<string>("PaymentLinkToken")
                        .HasColumnType("text")
                        .HasColumnName("payment_link_token");

                    b.Property<string>("PdfUrl")
                        .HasColumnType("text")
                        .HasColumnName("pdf_url");

                    b.Property<decimal>("RoomRent")
                        .HasColumnType("numeric")
                        .HasColumnName("room_rent");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<decimal>("ServiceFee")
                        .HasColumnType("numeric")
                        .HasColumnName("service_fee");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("WaterAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("water_amount");

                    b.Property<int>("WaterNew")
                        .HasColumnType("integer")
                        .HasColumnName("water_new");

                    b.Property<int>("WaterOld")
                        .HasColumnType("integer")
                        .HasColumnName("water_old");

                    b.Property<decimal>("WaterPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("water_price");

                    b.HasKey("Id")
                        .HasName("p_k_invoices");

                    b.HasIndex("InvoiceCode")
                        .IsUnique()
                        .HasDatabaseName("i_x_invoices_invoice_code");

                    b.HasIndex("PaymentLinkToken")
                        .IsUnique()
                        .HasDatabaseName("i_x_invoices_payment_link_token");

                    b.HasIndex("ContractId", "BillingMonth")
                        .IsUnique()
                        .HasDatabaseName("i_x_invoices_contract_id_billing_month")
                        .HasFilter("\"Status\" != 3");

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("RentalOS.Domain.Entities.MaintenanceTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedToId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("priority");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_maintenance_tasks");

                    b.HasIndex("AssignedToId")
                        .HasDatabaseName("i_x_maintenance_tasks_assigned_to_id");

                    b.HasIndex("PropertyId")
                        .HasDatabaseName("i_x_maintenance_tasks_property_id");

                    b.ToTable("maintenance_tasks", (string)null);
                });

            modelBuilder.Entity("RentalOS.Domain.Entities.MeterReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ElectricityImage")
                        .HasColumnType("text")
                        .HasColumnName("electricity_image");

                    b.Property<int>("ElectricityReading")
                        .HasColumnType("integer")
                        .HasColumnName("electricity_reading");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateOnly>("ReadingDate")
                        .HasColumnType("date")
                        .HasColumnName("reading_date");

                    b.Property<Guid?>("RecordedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WaterImage")
                        .HasColumnType("text")
                        .HasColumnName("water_image");

                    b.Property<int>("WaterReading")
                        .HasColumnType("integer")
                        .HasColumnName("water_reading");

                    b.HasKey("Id")
                        .HasName("p_k_meter_readings");

                    b.HasIndex("RoomId", "ReadingDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("i_x_meter_readings_room_id_reading_date");

                    b.ToTable("meter_readings", (string)null);
                });

            modelBuilder.Entity("RentalOS.Domain.Entities.NotificationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("channel");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("ProviderRef")
                        .HasColumnType("text")
                        .HasColumnName("provider_ref");

                    b.Property<string>("RecipientEmail")
                        .HasColumnType("text")
                        .HasColumnName("recipient_email");

                    b.Property<string>("RecipientName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("recipient_name");

                    b.Property<string>("RecipientPhone")
                        .HasColumnType("text")
                        .HasColumnName("recipient_phone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_notification_logs");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("i_x_notification_logs_created_at");

                    b.ToTable("notification_logs", (string)null);
                });

            modelBuilder.Entity("RentalOS.Domain.Entities.PaymentLinkLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("p_k_payment_link_logs");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("i_x_payment_link_logs_invoice_id");

                    b.ToTable("payment_link_logs", (string)null);
                });

            modelBuilder.Entity("RentalOS.Domain.Entities.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("CoverImage")
                        .HasColumnType("text")
                        .HasColumnName("cover_image");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("District")
                        .HasColumnType("text")
                        .HasColumnName("district");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("images");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal?>("Lat")
                        .HasColumnType("numeric")
                        .HasColumnName("lat");

                    b.Property<decimal?>("Lng")
                        .HasColumnType("numeric")
                        .HasColumnName("lng");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("property_type");

                    b.Property<string>("Province")
                        .HasColumnType("text")
                        .HasColumnName("province");

                    b.Property<int>("TotalFloors")
                        .HasColumnType("integer")
                        .HasColumnName("total_floors");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Ward")
                        .HasColumnType("text")
                        .HasColumnName("ward");

                    b.HasKey("Id")
                        .HasName("p_k_properties");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("i_x_properties_owner_id");

                    b.ToTable("properties", (string)null);
                });

            modelBuilder.Entity("RentalOS.Domain.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_reviews");

                    b.HasIndex("PropertyId")
                        .HasDatabaseName("i_x_reviews_property_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_reviews_user_id");

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("RentalOS.Domain.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Amenities")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("amenities");

                    b.Property<decimal?>("AreaSqm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("area_sqm");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("base_price");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("ElectricityPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("electricity_price");

                    b.Property<int>("Floor")
                        .HasColumnType("integer")
                        .HasColumnName("floor");

                    b.Property<decimal>("GarbageFee")
                        .HasColumnType("numeric")
                        .HasColumnName("garbage_fee");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("images");

                    b.Property<decimal>("InternetFee")
                        .HasColumnType("numeric")
                        .HasColumnName("internet_fee");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("MaintenanceNote")
                        .HasColumnType("text")
                        .HasColumnName("maintenance_note");

                    b.Property<DateOnly?>("MaintenanceSince")
                        .HasColumnType("date")
                        .HasColumnName("maintenance_since");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("room_number");

                    b.Property<decimal>("ServiceFee")
                        .HasColumnType("numeric")
                        .HasColumnName("service_fee");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("WaterPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("water_price");

                    b.HasKey("Id")
                        .HasName("p_k_rooms");

                    b.HasIndex("PropertyId", "RoomNumber")
                        .IsUnique()
                        .HasDatabaseName("i_x_rooms_property_id_room_number");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("RentalOS.Domain.Entities.Setting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("group");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("p_k_settings");

                    b.HasIndex("Group", "Key")
                        .IsUnique()
                        .HasDatabaseName("i_x_settings_group_key");

                    b.ToTable("settings", (string)null);
                });

            modelBuilder.Entity("RentalOS.Domain.Entities.SubscriptionPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateOnly>("BillingFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly>("BillingTo")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Method")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Plan")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderRef")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProviderRef");

                    b.HasIndex("TenantId");

                    b.ToTable("subscription_payments", "public");
                });

            modelBuilder.Entity("RentalOS.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("OnboardingDone")
                        .HasColumnType("boolean");

                    b.Property<string>("OwnerEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<int>("Plan")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PlanExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SchemaName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("TrialEndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("tenants", "public");
                });

            modelBuilder.Entity("RentalOS.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("direction");

                    b.Property<Guid?>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("method");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("ProviderRef")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_ref");

                    b.Property<string>("ProviderResponse")
                        .HasColumnType("jsonb")
                        .HasColumnName("provider_response");

                    b.Property<string>("ReceiptUrl")
                        .HasColumnType("text")
                        .HasColumnName("receipt_url");

                    b.Property<Guid?>("RecordedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TransactionCode")
                        .HasColumnType("text")
                        .HasColumnName("transaction_code");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_transactions");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("i_x_transactions_invoice_id");

                    b.HasIndex("PaidAt")
                        .HasDatabaseName("i_x_transactions_paid_at");

                    b.HasIndex("ProviderRef")
                        .HasDatabaseName("i_x_transactions_provider_ref");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("RentalOS.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<Guid>>("AssignedPropertyIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("InviteExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InviteToken")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("InviteToken");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("RentalOS.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("RentalOS.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("RentalOS.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("RentalOS.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentalOS.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("RentalOS.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RentalOS.Domain.Entities.Address", b =>
                {
                    b.HasOne("RentalOS.Domain.Entities.Property", "Property")
                        .WithMany("Addresses")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("f_k_addresses_properties_property_id");

                    b.HasOne("RentalOS.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("f_k_addresses_users_user_id");

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RentalOS.Domain.Entities.AiConversation", b =>
                {
                    b.HasOne("RentalOS.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_ai_conversations_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RentalOS.Domain.Entities.Contract", b =>
                {
                    b.HasOne("RentalOS.Domain.Entities.Customer", "Customer")
                        .WithMany("Contracts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_contracts_customers_customer_id");

                    b.HasOne("RentalOS.Domain.Entities.Room", "Room")
                        .WithMany("Contracts")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_contracts_rooms_room_id");

                    b.Navigation("Customer");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("RentalOS.Domain.Entities.ContractCoTenant", b =>
                {
                    b.HasOne("RentalOS.Domain.Entities.Contract", "Contract")
                        .WithMany("CoTenants")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_contract_co_tenants_contracts_contract_id");

                    b.HasOne("RentalOS.Domain.Entities.Customer", "Customer")
                        .WithMany("CoTenantEntries")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_contract_co_tenants_customers_customer_id");

                    b.Navigation("Contract");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("RentalOS.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("RentalOS.Domain.Entities.Contract", "Contract")
                        .WithMany("Invoices")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_invoices_contracts_contract_id");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("RentalOS.Domain.Entities.MaintenanceTask", b =>
                {
                    b.HasOne("RentalOS.Domain.Entities.User", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToId")
                        .HasConstraintName("f_k_maintenance_tasks_users_assigned_to_id");

                    b.HasOne("RentalOS.Domain.Entities.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_maintenance_tasks_properties_property_id");

                    b.Navigation("AssignedTo");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("RentalOS.Domain.Entities.MeterReading", b =>
                {
                    b.HasOne("RentalOS.Domain.Entities.Room", "Room")
                        .WithMany("MeterReadings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_meter_readings_rooms_room_id");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("RentalOS.Domain.Entities.PaymentLinkLog", b =>
                {
                    b.HasOne("RentalOS.Domain.Entities.Invoice", "Invoice")
                        .WithMany("PaymentLinkLogs")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_payment_link_logs_invoices_invoice_id");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("RentalOS.Domain.Entities.Review", b =>
                {
                    b.HasOne("RentalOS.Domain.Entities.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_reviews_properties_property_id");

                    b.HasOne("RentalOS.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_reviews_users_user_id");

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RentalOS.Domain.Entities.Room", b =>
                {
                    b.HasOne("RentalOS.Domain.Entities.Property", "Property")
                        .WithMany("Rooms")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_rooms_properties_property_id");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("RentalOS.Domain.Entities.SubscriptionPayment", b =>
                {
                    b.HasOne("RentalOS.Domain.Entities.Tenant", "Tenant")
                        .WithMany("SubscriptionPayments")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RentalOS.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("RentalOS.Domain.Entities.Invoice", "Invoice")
                        .WithMany("Transactions")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_transactions_invoices_invoice_id");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("RentalOS.Domain.Entities.Contract", b =>
                {
                    b.Navigation("CoTenants");

                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("RentalOS.Domain.Entities.Customer", b =>
                {
                    b.Navigation("CoTenantEntries");

                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("RentalOS.Domain.Entities.Invoice", b =>
                {
                    b.Navigation("PaymentLinkLogs");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("RentalOS.Domain.Entities.Property", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("RentalOS.Domain.Entities.Room", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("MeterReadings");
                });

            modelBuilder.Entity("RentalOS.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("SubscriptionPayments");
                });
#pragma warning restore 612, 618
        }
    }
}
