using MediatR;
using Microsoft.EntityFrameworkCore;
using RentalOS.Application.Common.Interfaces;
using RentalOS.Application.Common.Models;
using RentalOS.Domain.Enums;

namespace RentalOS.Application.Modules.Invoices.Queries.GetInvoices;

public record GetInvoicesQuery : IRequest<Result<PagedResult<InvoiceDto>>>
{
    public Guid? PropertyId { get; init; }
    public Guid? ContractId { get; init; }
    public DateOnly? BillingMonth { get; init; }
    public InvoiceStatus? Status { get; init; }
    public string? Search { get; init; }
    public int PageNumber { get; init; } = 1;
    public int PageSize { get; init; } = 50;
}

public class GetInvoicesQueryHandler : IRequestHandler<GetInvoicesQuery, Result<PagedResult<InvoiceDto>>>
{
    private readonly IApplicationDbContext _context;

    public GetInvoicesQueryHandler(IApplicationDbContext context)
    {
        _context = context;
    }

    public async Task<Result<PagedResult<InvoiceDto>>> Handle(GetInvoicesQuery request, CancellationToken cancellationToken)
    {
        var query = _context.Invoices
            .Include(i => i.Contract)
                .ThenInclude(c => c.Customer)
            .Include(i => i.Contract)
                .ThenInclude(c => c.Room)
                    .ThenInclude(r => r.Property)
            .AsNoTracking()
            .AsQueryable();


        if (request.PropertyId.HasValue)
            query = query.Where(i => i.Contract.Room.PropertyId == request.PropertyId.Value);

        if (request.ContractId.HasValue)
            query = query.Where(i => i.ContractId == request.ContractId.Value);

        if (request.BillingMonth.HasValue)
        {
            var firstDay = new DateOnly(request.BillingMonth.Value.Year, request.BillingMonth.Value.Month, 1);
            query = query.Where(i => i.BillingMonth == firstDay);
        }

        if (request.Status.HasValue)
            query = query.Where(i => i.Status == request.Status.Value);

        if (!string.IsNullOrWhiteSpace(request.Search))
        {
            query = query.Where(i =>
                i.InvoiceCode.Contains(request.Search) ||
                i.Contract.Customer.FullName.Contains(request.Search) ||
                i.Contract.Room.RoomNumber.Contains(request.Search));
        }

        var totalCount = await query.CountAsync(cancellationToken);

        var items = await query
            .OrderByDescending(i => i.BillingMonth)
            .ThenByDescending(i => i.CreatedAt)
            .Skip((request.PageNumber - 1) * request.PageSize)
            .Take(request.PageSize)
            .Select(i => new InvoiceDto
            {
                Id = i.Id,
                InvoiceCode = i.InvoiceCode,
                ContractId = i.ContractId,
                CustomerName = i.Contract.Customer.FullName,
                RoomNumber = i.Contract.Room.RoomNumber,
                PropertyName = i.Contract.Room.Property.Name,
                BillingMonth = i.BillingMonth,
                DueDate = i.DueDate,
                TotalAmount = i.TotalAmount,
                Status = i.Status,
                PartialPaidAmount = i.PartialPaidAmount,
                PaymentLinkToken = i.PaymentLinkToken,
                SentAt = i.SentAt,
                PaidAt = i.PaidAt,
                PdfUrl = i.PdfUrl,
                IsAutoGenerated = i.IsAutoGenerated,
                ElectricityOld = i.ElectricityOld,
                ElectricityNew = i.ElectricityNew,
                ElectricityPrice = i.ElectricityPrice,
                ElectricityAmount = i.ElectricityAmount,
                WaterOld = i.WaterOld,
                WaterNew = i.WaterNew,
                WaterPrice = i.WaterPrice,
                WaterAmount = i.WaterAmount,
                RoomRent = i.RoomRent,
                ServiceFee = i.ServiceFee,
                InternetFee = i.InternetFee,
                GarbageFee = i.GarbageFee,
                OtherFees = i.OtherFees,
                OtherFeesNote = i.OtherFeesNote,
                Discount = i.Discount,
                DiscountNote = i.DiscountNote,
                Notes = i.Notes,
            })
            .ToListAsync(cancellationToken);

        return Result<PagedResult<InvoiceDto>>.Ok(new PagedResult<InvoiceDto>(items, totalCount, request.PageNumber, request.PageSize));
    }
}
